import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "~/styles/globals.css";
import FooterTemplate from "~/components/templates/footer/page";
import HeaderTemplate from "~/components/templates/header/page";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <HeaderTemplate />
        {children}
        <FooterTemplate />
      </body>
    </html>
  );
}
